In [3]:
import numpy as np, pandas as pd, matplotlib.pyplot as plt
import glob, functools, tqdm, PIL
from multiprocess import Pool
from PIL import Image
import io
import pathlib

im = Image.open('apple.jpg', 'r')
im2 = Image.open('apple2.jpg', 'r')
#im = Image.open({'path':glob.glob("../training/Motorola-X/(MotoX)1.jpg")})
pix = im.load()
print (im.size)
matrix = np.array(im.getdata())#convert the images as a set of pixels
print(matrix)

df = pd.DataFrame(data=matrix) #convert numpy array type to a df

im2.rotate(45).save('apple3.png') #rotating a photo omg!

(400, 400)
[[255 255 255]
 [255 255 255]
 [255 255 255]
 ...
 [255 255 255]
 [255 255 255]
 [255 255 255]]


Attempt 1 Aggregate Data

In [7]:
training = []
#"C:\Users\Nikkitha\Documents\COMPUTER ENGR\CMPE 188\project\train\HTC-1-M7\(HTC-1-M7)1.jpg"
for infile in glob.glob( "apples\*.jpg"):
    im = Image.open(infile)
    matrix = np.array(im.getdata())
    array = np.concatenate(training, matrix)

print(array)

TypeError: only integer scalar arrays can be converted to a scalar index

Attempt 2 Aggregate Data

In [6]:
import cv2
import os
import glob
img_dir = "\apples" # Enter Directory of all images 
data_path = os.path.join(img_dir,'*g')
files = glob.glob(data_path)
data = []
for f1 in files:
    img = cv2.imread(f1)
    data.append(img)
    
data

[]

Attempt 3 Aggregate Data

In [10]:
import cv2
import os
from skimage.io import imread_collection, imshow_collection, concatenate_images
import numpy as np

folder = 'apples/*.jpg'

col = imread_collection(folder) #Concatenate all images in the image collection into an array.

n = 2
#array = np.empty(shape=[1,n])
#imshow_collection(col)
w,h,l = 2,2,1
array = [[[0 for x in range(w)] for y in range(h)] for z in range(l)]
array = concatenate_images(col)
array

[[[0, 0], [0, 0]], [[0, 0], [0, 0]]]